const {app, BrowserWindow} = require('electron');
let win = null; // create an empty window

app.on('ready', function () {

  // Initialize the window with our desired dimensions
  win = new BrowserWindow({width: 1000, height: 600});

  // Load the html file that is auto-generated by vue.js
  win.loadURL(`${__dirname}/index.html`);

  // Remove window once app is closed
  win.on('closed', function () {
    win = null;
  });

});

//quit the app once closed
app.on('window-all-closed', function () {
  if (process.platform != 'darwin') {
    app.quit();
  }
});